### ISSUE TITLE
geneanno.exp.csv missing one line?

### ISSUE THREAD

**Issue by thouis** [FunctionLab/ExPecto#2]
geneanno.csv and geneanno.exp.csv have different numbers of lines:
```
~/ExPecto$ wc -l resources/geneanno.exp.csv resources/geneanno.csv
   24340 resources/geneanno.exp.csv
   24341 resources/geneanno.csv
```
I assume this it's the last one, but it would be good to know for sure.

**Comment by thouis** [comment]
By the way, the precomputed features match geneanno.exp.csv (one less for header).

```
~/ExPecto$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.load('./resources/Xreducedall.2002.npy').shape
(24339, 20020)
>>> 
```

**Comment by jzthree** [comment]
Thanks for the report! `geneanno.csv` and `geneanno.exp.csv` actually have the same number of genes (24339 without header). The numbers of rows are also the same when opened by pandas. The difference in `wc -l` report should be due to newline at the end of the file (there are some system differences too since my Mac OS X 10.13.5 is reporting a different number). I have made a commit in trying to fix this just in case.

**Comment by thouis** [comment]
Thank you, sorry for the confusion.
